"""
x402 ``upto`` scheme (Permit2) for BlockRun's EVM gateways.

Under ``exact`` the payer signs an EIP-3009 authorization for a fixed pre-call
quote, so a discount the gateway only learns after the call — a prompt-cache
hit, a short answer — can never reach an x402 caller. Under ``upto`` the payer
signs a Permit2 ``PermitWitnessTransferFrom`` for a CEILING, and the gateway
settles the ACTUAL amount (never more than the ceiling) once the call is done.

A gateway that offers upto lists it after ``exact`` in ``accepts``. This module
decides whether to take it, and signs it. The rule is that choosing upto must
never be worse than today's ``exact``:

* It is taken only when the 402 offers an EVM upto option carrying
  ``extra.facilitatorAddress`` for a network in :data:`EVM_NETWORKS`, and
* the wallet holds at least the ceiling in USDC, and
* Permit2 may already pull the ceiling (USDC ``allowance(owner, Permit2)``), or
  the 402 declares the ``eip2612GasSponsoring`` extension, in which case the
  wallet signs a gasless EIP-2612 permit to Permit2 and the facilitator submits
  the approval — so a wallet holding no ETH can still use upto.

Anything else — no RPC answer, a signing error, a ceiling over a spend limit, a
sponsored permit already in flight for this wallet — falls back to ``exact``
silently (debug log only). Solana is untouched: it only ever pays ``exact``.

Semantics match the official ``@x402/evm`` 2.28.0 client (``UptoEvmScheme``,
``createUptoPermit2Payload``, ``trySignEip2612PermitExtension``); the unit tests
pin a vector generated by that client (``scripts/gen-upto-vector.mjs``).

The private key is used ONLY for local signing and NEVER leaves the client.
"""

from __future__ import annotations

import base64
import json
import logging
import os
import re
import secrets
import threading
import time
from collections.abc import Awaitable
from dataclasses import dataclass
from typing import Any, Callable

import httpx
from eth_account.messages import encode_typed_data
from eth_utils.address import to_checksum_address

from .x402 import (
    _NETWORK_ALIASES,
    EVM_NETWORKS,
    signature_hex,
    with_builder_code_service_code,
)

logger = logging.getLogger(__name__)

# Canonical Uniswap Permit2 — the same address on every EVM chain.
PERMIT2_ADDRESS = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
# x402's upto proxy: the Permit2 `spender`. It only lets the facilitator bound
# in the witness settle, and only up to the permitted amount.
X402_UPTO_PERMIT2_PROXY_ADDRESS = "0x4020A4f3b7b90ccA423B9fabCc0CE57C6C240002"

EIP2612_GAS_SPONSORING_KEY = "eip2612GasSponsoring"
# The EIP-2612 permit approves Permit2 for exactly the per-call ceiling, as the
# official client does. Not MaxUint256: the upto proxy's `_executePermit`
# reverts with Permit2612AmountMismatch unless permit.value == permitted.amount,
# and CDP /verify rejects a MaxUint256 permit.
EIP2612_GAS_SPONSORING_VERSION = "1"

# `payment_scheme` values a client accepts. "auto" prefers upto when the rule
# above allows it; "exact" never signs upto.
PAYMENT_SCHEMES = ("auto", "exact")
PAYMENT_SCHEME_ENV = "BLOCKRUN_PAYMENT_SCHEME"

# Per-RPC timeout for the allowance / balance / nonce reads. These run on every
# upto-eligible call before signing, so they are kept short: a slow RPC falls
# through to the next one, and all of them failing falls back to exact.
RPC_TIMEOUT_SECONDS = 3.0

# ERC-20 / EIP-2612 view selectors.
_SEL_BALANCE_OF = "0x70a08231"  # balanceOf(address)
_SEL_ALLOWANCE = "0xdd62ed3e"  # allowance(address,address)
_SEL_NONCES = "0x7ecebe00"  # nonces(address)

_ADDRESS_RE = re.compile(r"^0x[0-9a-fA-F]{40}$")
_UINT_RE = re.compile(r"^[0-9]+$")

UPTO_PERMIT2_WITNESS_TYPES: dict[str, list[dict[str, str]]] = {
    "PermitWitnessTransferFrom": [
        {"name": "permitted", "type": "TokenPermissions"},
        {"name": "spender", "type": "address"},
        {"name": "nonce", "type": "uint256"},
        {"name": "deadline", "type": "uint256"},
        {"name": "witness", "type": "Witness"},
    ],
    "TokenPermissions": [
        {"name": "token", "type": "address"},
        {"name": "amount", "type": "uint256"},
    ],
    "Witness": [
        {"name": "to", "type": "address"},
        {"name": "facilitator", "type": "address"},
        {"name": "validAfter", "type": "uint256"},
    ],
}

EIP2612_PERMIT_TYPES: dict[str, list[dict[str, str]]] = {
    "Permit": [
        {"name": "owner", "type": "address"},
        {"name": "spender", "type": "address"},
        {"name": "value", "type": "uint256"},
        {"name": "nonce", "type": "uint256"},
        {"name": "deadline", "type": "uint256"},
    ],
}


class UptoUnavailable(Exception):
    """Upto cannot be used for this call; the caller falls back to exact."""


def resolve_payment_scheme(value: str | None) -> str:
    """The client's ``payment_scheme``: the argument, else ``BLOCKRUN_PAYMENT_SCHEME``, else "auto".

    Raises:
        ValueError: For anything other than "auto" or "exact".
    """
    raw = value if value is not None else os.environ.get(PAYMENT_SCHEME_ENV)
    scheme = (raw or "auto").strip().lower()
    if scheme not in PAYMENT_SCHEMES:
        source = "payment_scheme" if value is not None else PAYMENT_SCHEME_ENV
        raise ValueError(f'{source} must be one of {", ".join(PAYMENT_SCHEMES)}; got "{raw}"')
    return scheme


# ---------------------------------------------------------------------------
# Selecting the offer
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class UptoOption:
    """A 402's upto requirement, validated against the SDK's own chain table."""

    requirement: dict[str, Any]  # the accepts entry, echoed back as `accepted`
    network: str  # canonical CAIP-2
    chain_id: int
    usdc: str
    domain: dict[str, Any]  # USDC's EIP-712 domain (SDK-owned, never the 402's)
    rpcs: tuple[str, ...]
    amount: int  # ceiling, micro-USDC
    pay_to: str
    facilitator: str
    max_timeout_seconds: int
    gas_sponsoring: bool  # the 402 declared extensions.eip2612GasSponsoring

    @property
    def ceiling_usd(self) -> float:
        return self.amount / 1e6


def gas_sponsoring_declared(payment_required: dict[str, Any]) -> bool:
    """Whether the 402's top-level ``extensions`` declares ``eip2612GasSponsoring``."""
    extensions = payment_required.get("extensions")
    return isinstance(extensions, dict) and bool(extensions.get(EIP2612_GAS_SPONSORING_KEY))


def offers_upto(payment_required: dict[str, Any]) -> bool:
    """Whether any ``accepts`` entry is an upto requirement (usable or not)."""
    accepts = payment_required.get("accepts")
    return isinstance(accepts, list) and any(
        isinstance(o, dict) and o.get("scheme") == "upto" for o in accepts
    )


def find_upto_option(payment_required: dict[str, Any]) -> UptoOption | None:
    """The first upto requirement this SDK can sign, or ``None``.

    Same trust rule as ``exact`` (see ``EVM_NETWORKS``): the 402 selects a
    network the SDK knows and must ask for that network's USDC; the chain id and
    token domain come from the SDK's table. ``extra.facilitatorAddress`` is
    required — without it the witness cannot bind a settler, and the official
    client refuses too.
    """
    accepts = payment_required.get("accepts")
    if not isinstance(accepts, list):
        return None
    sponsoring = gas_sponsoring_declared(payment_required)
    for opt in accepts:
        if not isinstance(opt, dict) or opt.get("scheme") != "upto":
            continue
        try:
            option = _validate_upto_option(opt, sponsoring)
        except (TypeError, ValueError) as exc:
            logger.debug("x402 upto: ignoring upto offer (%s)", exc)
            continue
        return option
    return None


def _validate_upto_option(opt: dict[str, Any], sponsoring: bool) -> UptoOption:
    network = str(opt.get("network") or "")
    net = EVM_NETWORKS.get(_NETWORK_ALIASES.get(network, network))
    if net is None:
        raise ValueError(f"network {network!r} is not an EVM network this SDK signs on")

    asset = opt.get("asset")
    if not isinstance(asset, str) or asset.lower() != net["usdc"].lower():
        raise ValueError(f"asset {asset!r} is not USDC on {network}")

    raw_extra = opt.get("extra")
    extra: dict[str, Any] = raw_extra if isinstance(raw_extra, dict) else {}
    facilitator = extra.get("facilitatorAddress")
    if not isinstance(facilitator, str) or not _ADDRESS_RE.match(facilitator):
        raise ValueError("no extra.facilitatorAddress")

    pay_to = opt.get("payTo")
    if not isinstance(pay_to, str) or not _ADDRESS_RE.match(pay_to):
        raise ValueError(f"payTo {pay_to!r} is not an address")

    raw_amount = opt.get("amount") or opt.get("maxAmountRequired")
    if not _UINT_RE.match(str(raw_amount or "")) or int(str(raw_amount)) <= 0:
        raise ValueError(f"amount {raw_amount!r} is not a positive integer")

    timeout = opt.get("maxTimeoutSeconds", 300)
    if isinstance(timeout, bool) or not isinstance(timeout, int) or timeout <= 0:
        raise ValueError(f"maxTimeoutSeconds {timeout!r} is not a positive integer")

    return UptoOption(
        requirement=dict(opt),
        network=_NETWORK_ALIASES.get(network, network),
        chain_id=int(net["chain_id"]),
        usdc=to_checksum_address(net["usdc"]),
        domain=dict(net["domain"]),
        rpcs=tuple(net.get("rpcs") or ()),
        amount=int(str(raw_amount)),
        pay_to=to_checksum_address(pay_to),
        facilitator=to_checksum_address(facilitator),
        max_timeout_seconds=timeout,
        gas_sponsoring=sponsoring,
    )


# ---------------------------------------------------------------------------
# Chain reads (public RPC, eth_call only)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class UptoChainState:
    balance: int  # USDC balanceOf(owner)
    allowance: int  # USDC allowance(owner, Permit2)
    permit_nonce: int | None  # USDC nonces(owner); read only when a permit is needed


def _word(address: str) -> str:
    return address[2:].lower().rjust(64, "0")


def _eth_call_body(to: str, data: str) -> dict[str, Any]:
    return {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "eth_call",
        "params": [{"to": to, "data": data}, "latest"],
    }


def _parse_uint(payload: Any) -> int:
    """A uint256 eth_call result, strictly: an RPC error or empty return raises.

    Strict on purpose — a nonce misread as 0 signs a permit the token rejects,
    which would fail a call that ``exact`` would have paid for.
    """
    if not isinstance(payload, dict) or payload.get("error"):
        raise UptoUnavailable(f"eth_call error: {payload!r:.200}")
    result = payload.get("result")
    if not isinstance(result, str) or not result.startswith("0x") or len(result) <= 2:
        raise UptoUnavailable(f"eth_call returned {result!r:.80}")
    return int(result, 16)


def _state_calls(option: UptoOption, owner: str) -> tuple[tuple[str, str], tuple[str, str]]:
    return (
        (option.usdc, _SEL_BALANCE_OF + _word(owner)),
        (option.usdc, _SEL_ALLOWANCE + _word(owner) + _word(PERMIT2_ADDRESS)),
    )


def _nonce_call(option: UptoOption, owner: str) -> tuple[str, str]:
    return option.usdc, _SEL_NONCES + _word(owner)


def _needs_permit_nonce(option: UptoOption, allowance: int) -> bool:
    return option.gas_sponsoring and allowance < option.amount


def _read_state_sync(
    http: httpx.Client, url: str, option: UptoOption, owner: str
) -> UptoChainState:
    def call(to: str, data: str) -> int:
        resp = http.post(url, json=_eth_call_body(to, data))
        resp.raise_for_status()
        return _parse_uint(resp.json())

    (b_to, b_data), (a_to, a_data) = _state_calls(option, owner)
    balance = call(b_to, b_data)
    allowance = call(a_to, a_data)
    nonce = call(*_nonce_call(option, owner)) if _needs_permit_nonce(option, allowance) else None
    return UptoChainState(balance, allowance, nonce)


async def _read_state_async(
    http: httpx.AsyncClient, url: str, option: UptoOption, owner: str
) -> UptoChainState:
    async def call(to: str, data: str) -> int:
        resp = await http.post(url, json=_eth_call_body(to, data))
        resp.raise_for_status()
        return _parse_uint(resp.json())

    (b_to, b_data), (a_to, a_data) = _state_calls(option, owner)
    balance = await call(b_to, b_data)
    allowance = await call(a_to, a_data)
    nonce = (
        await call(*_nonce_call(option, owner)) if _needs_permit_nonce(option, allowance) else None
    )
    return UptoChainState(balance, allowance, nonce)


def read_upto_chain_state(
    option: UptoOption, owner: str, *, timeout: float = RPC_TIMEOUT_SECONDS
) -> UptoChainState:
    """Read balance, Permit2 allowance and (if a permit is needed) the EIP-2612 nonce.

    Tries each of the network's public RPCs in turn; raises
    :class:`UptoUnavailable` when none answers.
    """
    if not option.rpcs:
        raise UptoUnavailable(f"no public RPC configured for {option.network}")
    last: Exception | None = None
    for url in option.rpcs:
        try:
            with httpx.Client(timeout=timeout) as http:
                return _read_state_sync(http, url, option, owner)
        except Exception as exc:  # next RPC
            last = exc
    raise UptoUnavailable(f"every RPC for {option.network} failed: {last}") from last


async def aread_upto_chain_state(
    option: UptoOption, owner: str, *, timeout: float = RPC_TIMEOUT_SECONDS
) -> UptoChainState:
    """Async :func:`read_upto_chain_state` — the same reads, without blocking the loop."""
    if not option.rpcs:
        raise UptoUnavailable(f"no public RPC configured for {option.network}")
    last: Exception | None = None
    for url in option.rpcs:
        try:
            async with httpx.AsyncClient(timeout=timeout) as http:
                return await _read_state_async(http, url, option, owner)
        except Exception as exc:  # next RPC
            last = exc
    raise UptoUnavailable(f"every RPC for {option.network} failed: {last}") from last


# ---------------------------------------------------------------------------
# Deciding
# ---------------------------------------------------------------------------

# Sponsored permits this process signed and has not yet seen consumed:
# (network, owner) → (USDC nonce signed over, permit deadline). A permit lands
# only when the facilitator settles the call that carried it, and it approves
# just that call's ceiling, so Permit2's allowance is back near 0 afterwards and
# every sponsored call needs a fresh permit. Until one lands the chain still
# shows the old USDC nonce, and a second call would sign another permit over the
# SAME nonce: the first settlement consumes it and the second reverts on-chain
# (seen live on Base mainnet). So per wallet and network only one gas-sponsored
# upto payment is in flight; a call that would need a second pays exact.
#
# Read on every sponsored preflight: on-chain nonce > signed nonce → the permit
# was consumed, clear; ≤ and before the deadline → still in flight, pay exact;
# past the deadline → it can never land, clear.
_PERMITS_IN_FLIGHT: dict[tuple[str, str], tuple[int, int]] = {}
_PERMITS_LOCK = threading.Lock()


def _now() -> float:
    return time.time()


def _claim_permit_slot(network: str, owner: str, onchain_nonce: int, deadline: int) -> bool:
    """Atomically: if no permit is in flight for this wallet+network, record one
    over ``onchain_nonce`` (valid until ``deadline``) and return True."""
    key = (network, owner.lower())
    now = _now()
    with _PERMITS_LOCK:
        pending = _PERMITS_IN_FLIGHT.get(key)
        if pending is not None:
            signed_nonce, pending_deadline = pending
            if onchain_nonce <= signed_nonce and now < pending_deadline:
                return False
        _PERMITS_IN_FLIGHT[key] = (onchain_nonce, deadline)
        return True


def _release_permit_slot(network: str, owner: str, signed_nonce: int) -> None:
    """Forget a permit that was never sent (signing failed)."""
    key = (network, owner.lower())
    with _PERMITS_LOCK:
        pending = _PERMITS_IN_FLIGHT.get(key)
        if pending is not None and pending[0] == signed_nonce:
            del _PERMITS_IN_FLIGHT[key]


def plan_upto(option: UptoOption, state: UptoChainState) -> bool | None:
    """``False`` = upto with no permit, ``True`` = upto with a sponsored permit,
    ``None`` = fall back to exact."""
    if state.balance < option.amount:
        logger.debug(
            "x402 upto: USDC balance %s below ceiling %s; using exact",
            state.balance,
            option.amount,
        )
        return None
    if state.allowance >= option.amount:
        return False
    if option.gas_sponsoring and state.permit_nonce is not None:
        return True
    logger.debug(
        "x402 upto: Permit2 allowance %s below ceiling %s and no gas sponsoring; using exact",
        state.allowance,
        option.amount,
    )
    return None


# ---------------------------------------------------------------------------
# Signing
# ---------------------------------------------------------------------------


def permit2_witness_typed_data(
    *,
    chain_id: int,
    token: str,
    amount: int,
    nonce: int,
    deadline: int,
    pay_to: str,
    facilitator: str,
    valid_after: int = 0,
) -> dict[str, Any]:
    """The full EIP-712 message the upto payer signs (Permit2 domain, no version)."""
    return {
        "types": {
            "EIP712Domain": [
                {"name": "name", "type": "string"},
                {"name": "chainId", "type": "uint256"},
                {"name": "verifyingContract", "type": "address"},
            ],
            **UPTO_PERMIT2_WITNESS_TYPES,
        },
        "primaryType": "PermitWitnessTransferFrom",
        "domain": {
            "name": "Permit2",
            "chainId": chain_id,
            "verifyingContract": PERMIT2_ADDRESS,
        },
        "message": {
            "permitted": {"token": token, "amount": amount},
            "spender": X402_UPTO_PERMIT2_PROXY_ADDRESS,
            "nonce": nonce,
            "deadline": deadline,
            "witness": {"to": pay_to, "facilitator": facilitator, "validAfter": valid_after},
        },
    }


def eip2612_permit_typed_data(
    *, domain: dict[str, Any], owner: str, value: int, nonce: int, deadline: int
) -> dict[str, Any]:
    """The full EIP-712 message for a USDC ``permit(owner, Permit2, value, …)``."""
    return {
        "types": {
            "EIP712Domain": [
                {"name": "name", "type": "string"},
                {"name": "version", "type": "string"},
                {"name": "chainId", "type": "uint256"},
                {"name": "verifyingContract", "type": "address"},
            ],
            **EIP2612_PERMIT_TYPES,
        },
        "primaryType": "Permit",
        "domain": dict(domain),
        "message": {
            "owner": owner,
            "spender": PERMIT2_ADDRESS,
            "value": value,
            "nonce": nonce,
            "deadline": deadline,
        },
    }


def _sign(account: Any, full_message: dict[str, Any]) -> str:
    return signature_hex(account.sign_message(encode_typed_data(full_message=full_message)))


def merge_extensions(
    server: dict[str, Any] | None, client: dict[str, Any] | None
) -> dict[str, Any]:
    """Port of ``x402Client.mergeExtensions`` (@x402/core): client data adds
    fields, server-declared fields stay intact; a non-object replaces."""
    if not client:
        return dict(server or {})
    if not server:
        return dict(client)
    merged = dict(server)
    for key, client_value in client.items():
        server_value = merged.get(key)
        if not isinstance(server_value, dict) or not isinstance(client_value, dict):
            merged[key] = client_value
            continue
        merged[key] = _merge_server_wins(server_value, client_value)
    return merged


def _merge_server_wins(server: dict[str, Any], client: dict[str, Any]) -> dict[str, Any]:
    out = dict(server)
    for field, client_field in client.items():
        server_field = out.get(field)
        if isinstance(server_field, dict) and isinstance(client_field, dict):
            out[field] = _merge_server_wins(server_field, client_field)
        elif field not in out:
            out[field] = client_field
    return out


def create_upto_payment_payload(
    account: Any,
    option: UptoOption,
    *,
    resource_url: str,
    resource_description: str,
    extensions: dict[str, Any] | None = None,
    permit_nonce: int | None = None,
    now: int | None = None,
    nonce: int | None = None,
) -> str:
    """Sign an upto payment and return the base64 ``PAYMENT-SIGNATURE`` value.

    ``permit_nonce`` set → also sign the EIP-2612 permit (USDC → Permit2 for the
    ceiling) and attach it as ``extensions.eip2612GasSponsoring.info``.
    ``now`` / ``nonce`` exist for deterministic tests.
    """
    now = int(time.time()) if now is None else now
    deadline = now + option.max_timeout_seconds
    permit2_nonce = int.from_bytes(secrets.token_bytes(32), "big") if nonce is None else nonce
    owner = to_checksum_address(account.address)

    signature = _sign(
        account,
        permit2_witness_typed_data(
            chain_id=option.chain_id,
            token=option.usdc,
            amount=option.amount,
            nonce=permit2_nonce,
            deadline=deadline,
            pay_to=option.pay_to,
            facilitator=option.facilitator,
        ),
    )

    merged = with_builder_code_service_code(extensions)
    if permit_nonce is not None:
        info = {
            "from": owner,
            "asset": option.usdc,
            "spender": PERMIT2_ADDRESS,
            # Must equal permitted.amount: the proxy reverts otherwise.
            "amount": str(option.amount),
            "nonce": str(permit_nonce),
            "deadline": str(deadline),
            "signature": _sign(
                account,
                eip2612_permit_typed_data(
                    domain=option.domain,
                    owner=owner,
                    value=option.amount,
                    nonce=permit_nonce,
                    deadline=deadline,
                ),
            ),
            "version": EIP2612_GAS_SPONSORING_VERSION,
        }
        merged = merge_extensions(merged, {EIP2612_GAS_SPONSORING_KEY: {"info": info}})

    payment = {
        "x402Version": 2,
        "resource": {
            "url": resource_url,
            "description": resource_description,
            "mimeType": "application/json",
        },
        # The requirement exactly as offered: a server may match `accepted`
        # against its own accepts entry field for field.
        "accepted": dict(option.requirement),
        "payload": {
            "signature": signature,
            "permit2Authorization": {
                "from": owner,
                "permitted": {"token": option.usdc, "amount": str(option.amount)},
                "spender": X402_UPTO_PERMIT2_PROXY_ADDRESS,
                "nonce": str(permit2_nonce),
                "deadline": str(deadline),
                "witness": {
                    "to": option.pay_to,
                    "facilitator": option.facilitator,
                    "validAfter": "0",
                },
            },
        },
        "extensions": merged,
    }
    return base64.b64encode(json.dumps(payment).encode()).decode()


# ---------------------------------------------------------------------------
# One call: decide, then sign — or return None for exact
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class UptoPayment:
    header: str  # base64 PAYMENT-SIGNATURE
    amount: int  # signed ceiling, micro-USDC
    permit_attached: bool

    @property
    def ceiling_usd(self) -> float:
        return self.amount / 1e6


def _sign_planned(
    account: Any,
    option: UptoOption,
    state: UptoChainState,
    *,
    resource_url: str,
    resource_description: str,
    extensions: dict[str, Any] | None,
) -> UptoPayment | None:
    needs_permit = plan_upto(option, state)
    if needs_permit is None:
        return None
    if not needs_permit:
        # Permit2 can already pull the ceiling: no permit, whatever is in flight.
        header = create_upto_payment_payload(
            account,
            option,
            resource_url=resource_url,
            resource_description=resource_description,
            extensions=extensions,
        )
        return UptoPayment(header, option.amount, permit_attached=False)

    assert state.permit_nonce is not None  # plan_upto returns True only with one
    now = int(_now())
    if not _claim_permit_slot(
        option.network, account.address, state.permit_nonce, now + option.max_timeout_seconds
    ):
        logger.debug("x402 upto: a sponsored permit is still in flight; using exact")
        return None
    try:
        header = create_upto_payment_payload(
            account,
            option,
            resource_url=resource_url,
            resource_description=resource_description,
            extensions=extensions,
            permit_nonce=state.permit_nonce,
            now=now,
        )
    except Exception:
        _release_permit_slot(option.network, account.address, state.permit_nonce)
        raise
    return UptoPayment(header, option.amount, permit_attached=True)


def try_upto_payment(
    account: Any,
    option: UptoOption,
    payment_required: dict[str, Any],
    *,
    resource_url: str,
    resource_description: str,
    within_limits: Callable[[float], bool],
    read_state: Callable[[UptoOption, str], UptoChainState] | None = None,
) -> UptoPayment | None:
    """Sign upto if the policy allows it; ``None`` (never an exception) means use exact."""
    try:
        if not within_limits(option.ceiling_usd):
            logger.debug("x402 upto: ceiling $%.6f breaches a spend limit", option.ceiling_usd)
            return None
        reader = read_state or read_upto_chain_state
        state = reader(option, account.address)
        return _sign_planned(
            account,
            option,
            state,
            resource_url=resource_url,
            resource_description=resource_description,
            extensions=payment_required.get("extensions"),
        )
    except Exception as exc:
        logger.debug("x402 upto: falling back to exact (%s: %s)", type(exc).__name__, exc)
        return None


async def atry_upto_payment(
    account: Any,
    option: UptoOption,
    payment_required: dict[str, Any],
    *,
    resource_url: str,
    resource_description: str,
    within_limits: Callable[[float], bool],
    read_state: Callable[[UptoOption, str], Awaitable[UptoChainState]] | None = None,
) -> UptoPayment | None:
    """Async :func:`try_upto_payment`."""
    try:
        if not within_limits(option.ceiling_usd):
            logger.debug("x402 upto: ceiling $%.6f breaches a spend limit", option.ceiling_usd)
            return None
        reader = read_state or aread_upto_chain_state
        state = await reader(option, account.address)
        return _sign_planned(
            account,
            option,
            state,
            resource_url=resource_url,
            resource_description=resource_description,
            extensions=payment_required.get("extensions"),
        )
    except Exception as exc:
        logger.debug("x402 upto: falling back to exact (%s: %s)", type(exc).__name__, exc)
        return None


def settled_upto_amount(settlement: dict[str, Any] | None, ceiling: int) -> int | None:
    """The settled micro-USDC a ``PAYMENT-RESPONSE`` reports, if it reports one
    that is plausible for this ceiling (0 ≤ amount ≤ ceiling); else ``None``."""
    if not settlement:
        return None
    raw = settlement.get("amount_micro_usdc")
    if raw is None or not _UINT_RE.match(str(raw)):
        return None
    amount = int(str(raw))
    return amount if amount <= ceiling else None


__all__ = [
    "EIP2612_GAS_SPONSORING_KEY",
    "PAYMENT_SCHEMES",
    "PERMIT2_ADDRESS",
    "X402_UPTO_PERMIT2_PROXY_ADDRESS",
    "UptoChainState",
    "UptoOption",
    "UptoPayment",
    "UptoUnavailable",
    "aread_upto_chain_state",
    "atry_upto_payment",
    "create_upto_payment_payload",
    "eip2612_permit_typed_data",
    "find_upto_option",
    "gas_sponsoring_declared",
    "merge_extensions",
    "offers_upto",
    "permit2_witness_typed_data",
    "plan_upto",
    "read_upto_chain_state",
    "resolve_payment_scheme",
    "settled_upto_amount",
    "try_upto_payment",
]
