"""x402 ``upto`` (Permit2) payments.

What these tests pin:

1. **Wire compatibility** — for fixed inputs the Python signer produces the
   byte-identical Permit2 witness signature, EIP-2612 permit signature and
   payload fields as the official ``@x402/evm`` 2.28.0 client. The vector in
   ``x402_upto_reference_vector.json`` was generated by that client
   (``scripts/gen-upto-vector.mjs``), not by this code.
2. **Selection policy** — upto is chosen only when the 402 offers it with a
   facilitator, the wallet holds the ceiling, and Permit2 may already pull it
   or the gateway sponsors the approval. Every other case — and every error —
   signs ``exact`` exactly as before.
3. **Rejection** — an upto payment the gateway refuses before serving anything
   is retried once with exact; a 2xx is never retried.
4. **Accounting** — the upto ceiling is never booked as a confirmed charge.
"""

from __future__ import annotations

import asyncio
import base64
import json
from pathlib import Path
from typing import Any

import httpx
import pytest
from eth_account import Account
from eth_account.messages import _hash_eip191_message, encode_typed_data

from blockrun_llm import AsyncLLMClient, LLMClient, cache
from blockrun_llm import x402_upto as upto
from blockrun_llm.tx_log import format_row
from blockrun_llm.types import PaymentError
from blockrun_llm.x402_upto import (
    PERMIT2_ADDRESS,
    X402_UPTO_PERMIT2_PROXY_ADDRESS,
    UptoChainState,
    create_upto_payment_payload,
    eip2612_permit_typed_data,
    find_upto_option,
    merge_extensions,
    permit2_witness_typed_data,
    plan_upto,
    resolve_payment_scheme,
)

from ..helpers import TEST_ACCOUNT, TEST_PRIVATE_KEY, TEST_RECIPIENT, build_chat_response

# The real chain readers, captured before the autouse fixture replaces them.
REAL_READ = upto.read_upto_chain_state
REAL_AREAD = upto.aread_upto_chain_state

VECTOR = json.loads((Path(__file__).parent / "x402_upto_reference_vector.json").read_text())
REQ = VECTOR["inputs"]["requirements"]
NOW = int(VECTOR["inputs"]["nowSeconds"])
NONCE_0x11 = int.from_bytes(b"\x11" * 32, "big")

USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
FACILITATOR = "0x97AcCe27D5069544480BDe0F04D9F47d7422a016"
MESSAGES = [{"role": "user", "content": "hi"}]

EXACT_AMOUNT = "1000"  # $0.001 — what exact signs
UPTO_CEILING = "50000"  # $0.05 — the upto ceiling (full max_tokens)

SPONSORING_DECL = {
    "info": {
        "description": "The facilitator accepts EIP-2612 gasless Permit to `Permit2` canonical contract.",
        "version": "1",
    },
    "schema": {"type": "object"},
}


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------


def exact_entry(amount: str = EXACT_AMOUNT) -> dict[str, Any]:
    return {
        "scheme": "exact",
        "network": "eip155:8453",
        "amount": amount,
        "asset": USDC_BASE,
        "payTo": TEST_RECIPIENT,
        "maxTimeoutSeconds": 300,
        "extra": {"name": "USD Coin", "version": "2"},
    }


def upto_entry(amount: str = UPTO_CEILING, **overrides: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "scheme": "upto",
        "network": "eip155:8453",
        "amount": amount,
        "asset": USDC_BASE,
        "payTo": TEST_RECIPIENT,
        "maxTimeoutSeconds": 300,
        "extra": {"name": "USD Coin", "version": "2", "facilitatorAddress": FACILITATOR},
    }
    entry.update(overrides)
    return entry


def payment_required(
    *, with_upto: bool = True, sponsoring: bool = False, upto: dict | None = None
) -> dict[str, Any]:
    accepts = [exact_entry()]
    if with_upto:
        accepts.append(upto or upto_entry())
    extensions: dict[str, Any] = {"builder-code": {"info": {"a": ["app"]}}}
    if sponsoring:
        extensions["eip2612GasSponsoring"] = SPONSORING_DECL
    return {
        "x402Version": 2,
        "accepts": accepts,
        "resource": {
            "url": "https://blockrun.ai/api/v1/chat/completions",
            "description": "AI model inference",
        },
        "extensions": extensions,
    }


def b64(obj: dict) -> str:
    return base64.b64encode(json.dumps(obj).encode()).decode()


def decode(header: str) -> dict[str, Any]:
    return json.loads(base64.b64decode(header))


def settlement_header(amount: str | None = None) -> str:
    data: dict[str, Any] = {
        "success": True,
        "transaction": "0x" + "ab" * 32,
        "network": "eip155:8453",
    }
    if amount is not None:
        data["amount"] = amount
    return b64(data)


class Gateway:
    """A MockTransport gateway: 402 on the unpaid call, then scripted answers
    for each paid call. Records every PAYMENT-SIGNATURE it receives."""

    def __init__(
        self,
        pr: dict[str, Any],
        paid: list[httpx.Response] | None = None,
        *,
        price_usd: str | None = None,
        header: bool = True,
    ):
        self.pr = pr
        self.paid = list(paid or [])
        self.signed: list[dict[str, Any]] = []
        self.price_usd = price_usd
        self.header = header

    def __call__(self, request: httpx.Request) -> httpx.Response:
        sig = request.headers.get("PAYMENT-SIGNATURE")
        if sig is None:
            if self.header:
                return httpx.Response(
                    402,
                    json={"error": "Payment Required"},
                    headers={"payment-required": b64(self.pr)},
                )
            body: dict[str, Any] = {**self.pr, "x402": True}
            if self.price_usd is not None:
                body["price"] = {"amount": self.price_usd, "currency": "USD"}
            return httpx.Response(402, json=body)
        self.signed.append(decode(sig))
        if self.paid:
            return self.paid.pop(0)
        return httpx.Response(
            200, json=build_chat_response(), headers={"PAYMENT-RESPONSE": settlement_header()}
        )

    @property
    def schemes(self) -> list[str]:
        return [s["accepted"]["scheme"] for s in self.signed]


def ok(amount: str | None = None) -> httpx.Response:
    return httpx.Response(
        200, json=build_chat_response(), headers={"PAYMENT-RESPONSE": settlement_header(amount)}
    )


def verify_failed() -> httpx.Response:
    return httpx.Response(
        402, json={"error": "Payment verification failed", "debug": "permit2_allowance_required"}
    )


def sync_client(gw: Gateway, **kwargs: Any) -> LLMClient:
    client = LLMClient(private_key=TEST_PRIVATE_KEY, **kwargs)
    client._client = httpx.Client(transport=httpx.MockTransport(gw))
    return client


def async_client(gw: Gateway, **kwargs: Any) -> AsyncLLMClient:
    client = AsyncLLMClient(private_key=TEST_PRIVATE_KEY, **kwargs)
    client._client = httpx.AsyncClient(transport=httpx.MockTransport(gw))
    return client


@pytest.fixture(autouse=True)
def _isolate(tmp_path, monkeypatch):
    """Keep the local archive out of ~/.blockrun, clear the permit registry,
    and make any unmocked chain read fail loudly rather than hit the network."""
    monkeypatch.setattr(cache, "CACHE_DIR", tmp_path / "cache")
    monkeypatch.setattr(cache, "DATA_DIR", tmp_path / "data")
    monkeypatch.setattr(cache, "COST_LOG_PATH", tmp_path / "cost_log.jsonl")
    monkeypatch.delenv(upto.PAYMENT_SCHEME_ENV, raising=False)
    upto._PERMITS_IN_FLIGHT.clear()
    upto._PERMIT_PREFLIGHT.clear()

    def no_network(*_a: Any, **_kw: Any) -> Any:
        raise AssertionError("unmocked chain read")

    monkeypatch.setattr(upto, "read_upto_chain_state", no_network)
    monkeypatch.setattr(upto, "aread_upto_chain_state", no_network)
    yield
    upto._PERMITS_IN_FLIGHT.clear()
    upto._PERMIT_PREFLIGHT.clear()


class Chain:
    """Scripted chain state for the upto reads (sync and async)."""

    def __init__(
        self,
        *,
        balance: int = 10**9,
        allowance: int = 10**9,
        nonce: int = 7,
        fail: bool = False,
    ):
        self.balance, self.allowance, self.nonce, self.fail = balance, allowance, nonce, fail
        self.reads = 0

    def state(self, option: upto.UptoOption, owner: str) -> UptoChainState:
        self.reads += 1
        if self.fail:
            raise upto.UptoUnavailable("every RPC failed")
        assert owner == TEST_ACCOUNT.address
        need = option.gas_sponsoring and self.allowance < option.amount
        return UptoChainState(self.balance, self.allowance, self.nonce if need else None)

    def install(self, monkeypatch: pytest.MonkeyPatch) -> Chain:
        monkeypatch.setattr(upto, "read_upto_chain_state", self.state)

        async def astate(option: upto.UptoOption, owner: str) -> UptoChainState:
            return self.state(option, owner)

        monkeypatch.setattr(upto, "aread_upto_chain_state", astate)
        return self


# ---------------------------------------------------------------------------
# 1. Wire compatibility with the official client
# ---------------------------------------------------------------------------


class TestReferenceVector:
    def _option(self, sponsoring: bool):
        pr = {"x402Version": 2, "accepts": [REQ]}
        if sponsoring:
            pr["extensions"] = {"eip2612GasSponsoring": {"info": {"version": "1"}}}
        option = find_upto_option(pr)
        assert option is not None
        return option, pr

    def test_constants_match_reference(self):
        assert PERMIT2_ADDRESS == VECTOR["constants"]["PERMIT2_ADDRESS"]
        assert X402_UPTO_PERMIT2_PROXY_ADDRESS == VECTOR["constants"]["x402UptoPermit2ProxyAddress"]

    def test_permit2_typed_data_hash_matches_viem(self):
        option, _ = self._option(False)
        typed = permit2_witness_typed_data(
            chain_id=8453,
            token=option.usdc,
            amount=option.amount,
            nonce=NONCE_0x11,
            deadline=NOW + 300,
            pay_to=option.pay_to,
            facilitator=option.facilitator,
        )
        digest = _hash_eip191_message(encode_typed_data(full_message=typed))
        assert "0x" + digest.hex() == VECTOR["permit2Digest"]

    def test_eip2612_typed_data_hash_matches_viem(self):
        option, _ = self._option(True)
        typed = eip2612_permit_typed_data(
            domain=option.domain,
            owner=TEST_ACCOUNT.address,
            value=option.amount,
            nonce=7,
            deadline=NOW + 300,
        )
        digest = _hash_eip191_message(encode_typed_data(full_message=typed))
        assert "0x" + digest.hex() == VECTOR["eip2612Digest"]

    def test_bare_payload_is_byte_identical(self):
        option, pr = self._option(False)
        payment = decode(
            create_upto_payment_payload(
                TEST_ACCOUNT,
                option,
                resource_url="https://blockrun.ai/api/v1/chat/completions",
                resource_description="d",
                extensions=pr.get("extensions"),
                now=NOW,
                nonce=NONCE_0x11,
            )
        )
        assert payment["payload"] == VECTOR["bare"]["payload"]
        assert "eip2612GasSponsoring" not in payment["extensions"]

    def test_sponsored_payload_is_byte_identical(self):
        option, pr = self._option(True)
        payment = decode(
            create_upto_payment_payload(
                TEST_ACCOUNT,
                option,
                resource_url="https://blockrun.ai/api/v1/chat/completions",
                resource_description="d",
                extensions=pr["extensions"],
                permit_nonce=7,
                now=NOW,
                nonce=NONCE_0x11,
            )
        )
        expected = VECTOR["sponsored"]
        assert payment["payload"] == expected["payload"]
        info = payment["extensions"]["eip2612GasSponsoring"]["info"]
        assert info == expected["extensions"]["eip2612GasSponsoring"]["info"]

    def test_permit_value_equals_permitted_amount(self):
        """The upto proxy reverts (Permit2612AmountMismatch) unless the EIP-2612
        permit's value is exactly the Permit2 permitted amount — so MaxUint256
        (or anything but the ceiling) is a signed payment that cannot settle."""
        option, pr = self._option(True)
        payment = decode(
            create_upto_payment_payload(
                TEST_ACCOUNT,
                option,
                resource_url="u",
                resource_description="d",
                extensions=pr["extensions"],
                permit_nonce=7,
            )
        )
        info = payment["extensions"]["eip2612GasSponsoring"]["info"]
        permitted = payment["payload"]["permit2Authorization"]["permitted"]["amount"]
        assert info["amount"] == permitted == REQ["amount"]
        # …and the signature is over that value, not just the JSON field.
        typed = eip2612_permit_typed_data(
            domain=option.domain,
            owner=TEST_ACCOUNT.address,
            value=int(permitted),
            nonce=7,
            deadline=int(info["deadline"]),
        )
        signer = Account.recover_message(
            encode_typed_data(full_message=typed), signature=info["signature"]
        )
        assert signer == TEST_ACCOUNT.address

    def test_signatures_recover_to_the_payer(self):
        auth = VECTOR["sponsored"]["payload"]["permit2Authorization"]
        typed = permit2_witness_typed_data(
            chain_id=8453,
            token=auth["permitted"]["token"],
            amount=int(auth["permitted"]["amount"]),
            nonce=int(auth["nonce"]),
            deadline=int(auth["deadline"]),
            pay_to=auth["witness"]["to"],
            facilitator=auth["witness"]["facilitator"],
        )
        signer = Account.recover_message(
            encode_typed_data(full_message=typed),
            signature=VECTOR["sponsored"]["payload"]["signature"],
        )
        assert signer == TEST_ACCOUNT.address


class TestPayloadEnvelope:
    def test_envelope_matches_exact_and_echoes_the_requirement(self):
        pr = payment_required(sponsoring=True)
        option = find_upto_option(pr)
        payment = decode(
            create_upto_payment_payload(
                TEST_ACCOUNT,
                option,
                resource_url="https://blockrun.ai/api/v1/chat/completions",
                resource_description="AI model inference",
                extensions=pr["extensions"],
                permit_nonce=3,
            )
        )
        assert payment["x402Version"] == 2
        assert payment["accepted"] == upto_entry()  # verbatim, facilitatorAddress included
        assert payment["resource"]["url"] == "https://blockrun.ai/api/v1/chat/completions"
        # BlockRun's builder service code merged in, the server's app code kept.
        assert payment["extensions"]["builder-code"]["info"] == {"a": ["app"], "s": ["blockrun"]}
        # @x402/core merge semantics: server-declared fields stay, client fields added.
        info = payment["extensions"]["eip2612GasSponsoring"]["info"]
        assert info["description"] == SPONSORING_DECL["info"]["description"]
        assert info["version"] == "1"
        assert info["spender"] == PERMIT2_ADDRESS
        assert info["amount"] == UPTO_CEILING  # must equal permitted.amount
        assert info["nonce"] == "3"
        assert info["deadline"] == payment["payload"]["permit2Authorization"]["deadline"]
        assert payment["extensions"]["eip2612GasSponsoring"]["schema"] == {"type": "object"}

    def test_nonce_is_random_256_bit_decimal(self):
        option = find_upto_option(payment_required())
        nonces = {
            decode(
                create_upto_payment_payload(
                    TEST_ACCOUNT, option, resource_url="u", resource_description="d"
                )
            )["payload"]["permit2Authorization"]["nonce"]
            for _ in range(3)
        }
        assert len(nonces) == 3
        assert all(n.isdigit() and int(n) < 2**256 for n in nonces)

    def test_merge_extensions_non_object_replaces(self):
        assert merge_extensions(
            {"a": 1, "b": {"x": 1}}, {"a": {"y": 2}, "b": {"x": 9, "z": 3}}
        ) == {
            "a": {"y": 2},
            "b": {"x": 1, "z": 3},
        }


# ---------------------------------------------------------------------------
# 2. Selection policy
# ---------------------------------------------------------------------------


class TestFindOption:
    def test_valid_offer(self):
        option = find_upto_option(payment_required(sponsoring=True))
        assert option is not None
        assert option.amount == int(UPTO_CEILING)
        assert option.facilitator == FACILITATOR
        assert option.gas_sponsoring is True
        assert option.chain_id == 8453

    @pytest.mark.parametrize(
        "bad",
        [
            upto_entry(extra={"name": "USD Coin", "version": "2"}),  # no facilitatorAddress
            upto_entry(asset="0x0000000000000000000000000000000000000001"),  # not USDC
            upto_entry(network="eip155:1"),  # a network this SDK does not sign on
            upto_entry(network="solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"),  # Solana: exact only
            upto_entry(amount="0"),
            upto_entry(amount="-5"),
            upto_entry(payTo="nope"),
            upto_entry(maxTimeoutSeconds=0),
        ],
    )
    def test_unusable_offer_is_ignored(self, bad):
        assert find_upto_option(payment_required(upto=bad)) is None

    def test_no_upto_offer(self):
        assert find_upto_option(payment_required(with_upto=False)) is None

    def test_v1_max_amount_required(self):
        entry = upto_entry()
        entry["maxAmountRequired"] = entry.pop("amount")
        option = find_upto_option(payment_required(upto=entry))
        assert option is not None and option.amount == int(UPTO_CEILING)


class TestPlan:
    option = find_upto_option(payment_required())
    sponsored = find_upto_option(payment_required(sponsoring=True))
    ceiling = int(UPTO_CEILING)

    def test_allowance_covers_ceiling(self):
        assert plan_upto(self.option, UptoChainState(self.ceiling, self.ceiling, None)) is False

    def test_no_allowance_no_sponsoring_is_exact(self):
        assert plan_upto(self.option, UptoChainState(10**9, self.ceiling - 1, None)) is None

    def test_no_allowance_with_sponsoring_needs_permit(self):
        assert plan_upto(self.sponsored, UptoChainState(10**9, 0, 4)) is True

    def test_balance_below_ceiling_is_exact(self):
        """Exact might fit a wallet the ceiling does not: never worse than today."""
        assert plan_upto(self.sponsored, UptoChainState(self.ceiling - 1, 10**9, None)) is None


class TestResolveScheme:
    def test_default_auto(self):
        assert resolve_payment_scheme(None) == "auto"

    def test_env(self, monkeypatch):
        monkeypatch.setenv(upto.PAYMENT_SCHEME_ENV, "EXACT")
        assert resolve_payment_scheme(None) == "exact"

    def test_argument_beats_env(self, monkeypatch):
        monkeypatch.setenv(upto.PAYMENT_SCHEME_ENV, "exact")
        assert resolve_payment_scheme("auto") == "auto"

    def test_invalid(self):
        with pytest.raises(ValueError, match="payment_scheme"):
            resolve_payment_scheme("upto")

    def test_client_rejects_invalid(self):
        with pytest.raises(ValueError):
            LLMClient(private_key=TEST_PRIVATE_KEY, payment_scheme="cheapest")


class TestClientSelection:
    def test_prefers_upto_with_allowance(self, monkeypatch):
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required())
        response = sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        sent = gw.signed[0]
        auth = sent["payload"]["permit2Authorization"]
        assert auth["permitted"] == {"token": USDC_BASE, "amount": UPTO_CEILING}
        assert auth["spender"] == X402_UPTO_PERMIT2_PROXY_ADDRESS
        assert auth["witness"]["facilitator"] == FACILITATOR
        assert "eip2612GasSponsoring" not in sent["extensions"]
        assert response.payment_scheme == "upto"
        assert chain.reads == 1

    def test_sponsored_permit_attached_when_no_allowance(self, monkeypatch):
        Chain(allowance=0, nonce=11).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        info = gw.signed[0]["extensions"]["eip2612GasSponsoring"]["info"]
        assert info["nonce"] == "11" and info["amount"] == UPTO_CEILING
        # The permit's value must equal Permit2's permitted amount.
        assert (
            gw.signed[0]["payload"]["permit2Authorization"]["permitted"]["amount"] == UPTO_CEILING
        )
        assert info["from"] == TEST_ACCOUNT.address

    def test_sponsoring_declared_but_allowance_suffices_skips_permit(self, monkeypatch):
        Chain(allowance=10**9).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        # The server's declaration is echoed (as @x402/core does) but carries no signed permit.
        assert "signature" not in gw.signed[0]["extensions"]["eip2612GasSponsoring"]["info"]

    def test_no_allowance_no_sponsoring_falls_back(self, monkeypatch):
        Chain(allowance=0).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=False))
        response = sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert gw.signed[0]["payload"]["authorization"]["value"] == EXACT_AMOUNT
        assert response.payment_scheme == "exact"
        assert response.cost_usd == pytest.approx(0.001)

    def test_rpc_failure_falls_back(self, monkeypatch):
        Chain(fail=True).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]

    def test_signing_error_falls_back(self, monkeypatch):
        Chain().install(monkeypatch)

        def boom(*_a, **_kw):
            raise RuntimeError("signer exploded")

        monkeypatch.setattr(upto, "create_upto_payment_payload", boom)
        gw = Gateway(payment_required())
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]

    def test_missing_facilitator_never_reads_chain(self, monkeypatch):
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required(upto=upto_entry(extra={"name": "USD Coin", "version": "2"})))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert chain.reads == 0

    def test_opt_out_argument(self, monkeypatch):
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw, payment_scheme="exact").chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert chain.reads == 0

    def test_opt_out_env(self, monkeypatch):
        monkeypatch.setenv(upto.PAYMENT_SCHEME_ENV, "exact")
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert chain.reads == 0

    def test_insufficient_balance_falls_back(self, monkeypatch):
        Chain(balance=int(UPTO_CEILING) - 1).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]

    def test_ceiling_over_per_call_limit_signs_exact_instead_of_refusing(self, monkeypatch):
        """The cap is checked against the ceiling; a ceiling over the cap is not a
        refusal when exact fits under it."""
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required())
        response = sync_client(gw, max_cost_per_call=0.01).chat_completion(
            "deepseek/deepseek-chat", MESSAGES
        )
        assert gw.schemes == ["exact"]
        assert response.cost_usd == pytest.approx(0.001)
        assert chain.reads == 0  # refused on the ceiling before any chain read

    def test_exact_fallback_books_its_own_amount_not_the_ceiling_price(self, monkeypatch):
        """A gateway offering upto quotes `price` at the ceiling; exact must not
        book (or cap on) that number."""
        Chain(allowance=0).install(monkeypatch)
        gw = Gateway(payment_required(), header=False, price_usd="0.050000")
        client = sync_client(gw, max_cost_per_call=0.01)
        response = client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert response.cost_usd == pytest.approx(0.001)
        assert client.get_spending()["total_usd"] == pytest.approx(0.001)

    def test_exact_only_402_is_unchanged(self, monkeypatch):
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required(with_upto=False))
        response = sync_client(gw).chat_completion("openai/gpt-5.2", MESSAGES)
        assert gw.schemes == ["exact"]
        assert chain.reads == 0
        assert response.payment_scheme == "exact"
        assert response.cost_is_ceiling is False

    def test_permit_in_flight_pays_exact_until_nonce_is_consumed(self, monkeypatch):
        """Per wallet only one gas-sponsored upto payment is in flight: while the
        on-chain USDC nonce still equals the one signed over (and the permit has
        not expired), a call that would need another permit pays exact. Once the
        nonce moves, the next permit is signed over the new one."""
        chain = Chain(allowance=0, nonce=5).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        client = sync_client(gw)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # permit over nonce 5
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # nonce still 5 → exact
        chain.nonce = 6  # the first permit settled (and its allowance was spent)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "upto"]
        nonces = [
            s["extensions"]["eip2612GasSponsoring"]["info"]["nonce"]
            for s in gw.signed
            if s["accepted"]["scheme"] == "upto"
        ]
        assert nonces == ["5", "6"]

    def test_permit_in_flight_cleared_after_deadline(self, monkeypatch):
        clock = [1_000_000.0]
        monkeypatch.setattr(upto, "_now", lambda: clock[0])
        Chain(allowance=0, nonce=5).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))  # maxTimeoutSeconds 300
        client = sync_client(gw)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # permit, deadline +300
        clock[0] += 299
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # in flight → exact
        clock[0] += 1  # at the deadline the permit can no longer land
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "upto"]
        assert gw.signed[2]["extensions"]["eip2612GasSponsoring"]["info"]["nonce"] == "5"

    def test_allowance_covering_ceiling_needs_no_permit_even_in_flight(self, monkeypatch):
        chain = Chain(allowance=0, nonce=5).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        client = sync_client(gw)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # permit over nonce 5
        chain.allowance = int(UPTO_CEILING)  # e.g. an approval made elsewhere
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "upto"]
        assert "signature" not in gw.signed[1]["extensions"]["eip2612GasSponsoring"]["info"]

    def test_permit_guard_is_per_wallet_and_network(self):
        far = int(upto._now()) + 300
        assert upto._claim_permit_slot("eip155:8453", "0xAAA", 5, far)
        assert not upto._claim_permit_slot("eip155:8453", "0xaaa", 5, far)
        assert upto._claim_permit_slot("eip155:8453", "0xBBB", 5, far)
        assert upto._claim_permit_slot("eip155:84532", "0xAAA", 5, far)
        assert upto._claim_permit_slot("eip155:8453", "0xAAA", 6, far)  # nonce moved

    def test_signing_failure_releases_the_slot(self, monkeypatch):
        Chain(allowance=0, nonce=5).install(monkeypatch)
        real = upto.create_upto_payment_payload
        calls = [0]

        def flaky(*a, **kw):
            calls[0] += 1
            if calls[0] == 1:
                raise RuntimeError("signer hiccup")
            return real(*a, **kw)

        monkeypatch.setattr(upto, "create_upto_payment_payload", flaky)
        gw = Gateway(payment_required(sponsoring=True))
        client = sync_client(gw)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # error → exact
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # slot free → permit
        assert gw.schemes == ["exact", "upto"]


class TestConcurrentPermits:
    """Three concurrent calls in ONE client, chain at allowance 0 / nonce 6:
    exactly one signs a permit, the other two pay exact."""

    @staticmethod
    def _permits(gw: Gateway) -> list[str]:
        return [
            s["extensions"]["eip2612GasSponsoring"]["info"]["nonce"]
            for s in gw.signed
            if s["accepted"]["scheme"] == "upto"
            and "signature" in s["extensions"]["eip2612GasSponsoring"]["info"]
        ]

    def test_threads(self, monkeypatch):
        import threading
        import time as _time
        from concurrent.futures import ThreadPoolExecutor

        chain = Chain(allowance=0, nonce=6)
        lock = threading.Lock()

        def slow_state(option, owner):
            _time.sleep(0.1)  # every call is inside its read at once
            with lock:
                return chain.state(option, owner)

        monkeypatch.setattr(upto, "read_upto_chain_state", slow_state)
        gw = Gateway(payment_required(sponsoring=True))
        client = sync_client(gw)
        with ThreadPoolExecutor(max_workers=3) as pool:
            list(
                pool.map(
                    lambda _: client.chat_completion("deepseek/deepseek-chat", MESSAGES), range(3)
                )
            )
        assert self._permits(gw) == ["6"]
        assert sorted(gw.schemes) == ["exact", "exact", "upto"]
        assert upto._PERMIT_PREFLIGHT == set()

    def test_asyncio_gather(self, monkeypatch):
        chain = Chain(allowance=0, nonce=6)

        async def slow_astate(option, owner):
            await asyncio.sleep(0.05)
            return chain.state(option, owner)

        monkeypatch.setattr(upto, "aread_upto_chain_state", slow_astate)
        gw = Gateway(payment_required(sponsoring=True))

        async def run():
            client = async_client(gw)
            await asyncio.gather(
                *(client.chat_completion("deepseek/deepseek-chat", MESSAGES) for _ in range(3))
            )

        asyncio.run(run())
        assert self._permits(gw) == ["6"]
        assert sorted(gw.schemes) == ["exact", "exact", "upto"]
        assert upto._PERMIT_PREFLIGHT == set()

    def test_marker_holder_elsewhere_still_allows_upto_without_permit(self, monkeypatch):
        Chain(allowance=10**9).install(monkeypatch)
        assert upto._reserve_preflight("eip155:8453", TEST_ACCOUNT.address)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        assert "signature" not in gw.signed[0]["extensions"]["eip2612GasSponsoring"]["info"]

    def test_marker_holder_elsewhere_and_no_allowance_is_exact(self, monkeypatch):
        chain = Chain(allowance=0, nonce=6).install(monkeypatch)
        assert upto._reserve_preflight("eip155:8453", TEST_ACCOUNT.address)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]
        assert chain.reads == 1

    def test_marker_released_when_no_permit_or_signing_fails(self, monkeypatch):
        Chain(allowance=10**9).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True))
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert upto._PERMIT_PREFLIGHT == set()

        Chain(allowance=0, nonce=6).install(monkeypatch)
        monkeypatch.setattr(
            upto,
            "create_upto_payment_payload",
            lambda *a, **k: (_ for _ in ()).throw(RuntimeError()),
        )
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert upto._PERMIT_PREFLIGHT == set()
        assert upto._PERMITS_IN_FLIGHT == {}


# ---------------------------------------------------------------------------
# 3. Rejection → one exact retry
# ---------------------------------------------------------------------------


class TestRejection:
    def test_upto_rejected_then_exact_succeeds_and_is_remembered(self, monkeypatch):
        chain = Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), ok()])
        client = sync_client(gw)
        response = client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact"]
        assert response.payment_scheme == "exact"
        assert response.cost_usd == pytest.approx(0.001)
        assert client.get_spending() == {
            "total_usd": pytest.approx(0.001),
            "calls": 1,
            "ceiling_usd": 0.0,
        }
        # Remembered (for UPTO_REJECTION_TTL_SECONDS): straight to exact, no chain read.
        reads = chain.reads
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "exact"]
        assert chain.reads == reads

    def test_rejection_is_per_client(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), ok()])
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "upto"]

    def test_payment_code_4xx_body_counts_as_rejection(self, monkeypatch):
        Chain().install(monkeypatch)
        refused = httpx.Response(400, json={"error": "bad", "code": "PAYMENT_INVALID"})
        gw = Gateway(payment_required(), paid=[refused, ok()])
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact"]

    def test_exact_retry_also_rejected_surfaces_original_error(self, monkeypatch):
        Chain().install(monkeypatch)
        original = httpx.Response(400, json={"error": "Payment verification failed", "x": "upto"})
        second = httpx.Response(402, json={"error": "Payment verification failed", "x": "exact"})
        gw = Gateway(payment_required(), paid=[original, second])
        client = sync_client(gw)
        from blockrun_llm.types import APIError

        with pytest.raises(APIError) as exc:
            client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert exc.value.status_code == 400  # the upto refusal, not the exact one
        assert gw.schemes == ["upto", "exact"]  # no third attempt
        assert client.get_spending()["calls"] == 0

    def test_rejection_expires_after_the_ttl(self, monkeypatch):
        import blockrun_llm.client as client_mod

        Chain().install(monkeypatch)
        clock = {"t": 1000.0}
        monkeypatch.setattr(client_mod.time, "monotonic", lambda: clock["t"])
        gw = Gateway(payment_required(), paid=[verify_failed(), ok()])
        client = sync_client(gw)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "exact"]
        clock["t"] += client_mod.UPTO_REJECTION_TTL_SECONDS + 1
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact", "exact", "upto"]

    def test_rejection_after_a_5xx_replay_never_pays_exact(self, monkeypatch):
        # The first send may have been served and settled behind the 502; the
        # replay's "verification failed" is then the used Permit2 nonce. Paying
        # exact on top would charge twice.
        monkeypatch.setattr("time.sleep", lambda _s: None)
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[httpx.Response(502), verify_failed(), ok()])
        client = sync_client(gw)
        with pytest.raises(PaymentError):
            client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "upto"]
        assert client._upto_rejected == {}

    def test_async_rejection_after_a_5xx_replay_never_pays_exact(self, monkeypatch):
        async def no_sleep(_s):
            return None

        monkeypatch.setattr("asyncio.sleep", no_sleep)
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[httpx.Response(503), verify_failed(), ok()])

        async def run():
            await async_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)

        with pytest.raises(PaymentError):
            asyncio.run(run())
        assert gw.schemes == ["upto", "upto"]

    def test_exact_payment_rejected_is_never_retried(self, monkeypatch):
        Chain(allowance=0).install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), ok()])
        with pytest.raises(PaymentError):
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["exact"]

    def test_2xx_never_triggers_a_retry(self, monkeypatch):
        Chain().install(monkeypatch)
        # A 200 whose body even mentions payment failure is served, not retried.
        served = httpx.Response(
            200,
            json={**build_chat_response(), "code": "PAYMENT_INVALID"},
            headers={"PAYMENT-RESPONSE": settlement_header()},
        )
        gw = Gateway(payment_required(), paid=[served])
        client = sync_client(gw)
        response = client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        assert response.payment_scheme == "upto"
        assert client._upto_rejected == {}

    def test_non_payment_error_after_upto_is_not_retried(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[httpx.Response(400, json={"error": "bad request"})])
        from blockrun_llm.types import APIError

        with pytest.raises(APIError):
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]

    def test_async_upto_rejected_then_exact(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), ok()])

        async def run():
            client = async_client(gw)
            first = await client.chat_completion("deepseek/deepseek-chat", MESSAGES)
            await client.chat_completion("deepseek/deepseek-chat", MESSAGES)
            return first

        first = asyncio.run(run())
        assert gw.schemes == ["upto", "exact", "exact"]
        assert first.payment_scheme == "exact"

    def test_async_exact_retry_rejected_surfaces_original(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), verify_failed()])

        async def run():
            await async_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)

        with pytest.raises(PaymentError):
            asyncio.run(run())
        assert gw.schemes == ["upto", "exact"]


# ---------------------------------------------------------------------------
# 4. Accounting: a ceiling is not a charge
# ---------------------------------------------------------------------------


class TestAccounting:
    def test_ceiling_booked_and_labeled_without_settled_amount(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required())
        client = sync_client(gw)
        response = client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert response.cost_usd == pytest.approx(0.05)
        assert response.cost_is_ceiling is True
        assert client.get_spending() == {
            "total_usd": pytest.approx(0.05),
            "calls": 1,
            "ceiling_usd": pytest.approx(0.05),
        }
        row = json.loads(cache.COST_LOG_PATH.read_text().splitlines()[-1])
        assert row["cost_basis"] == "upto_ceiling"

    def test_settled_amount_from_payment_response_is_booked(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[ok(amount="1234")])
        client = sync_client(gw)
        response = client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert response.cost_usd == pytest.approx(0.001234)
        assert response.cost_is_ceiling is False
        assert client.get_spending()["ceiling_usd"] == 0.0
        row = json.loads(cache.COST_LOG_PATH.read_text().splitlines()[-1])
        assert row["cost_basis"] == "upto_settled"

    def test_settled_amount_above_ceiling_is_not_trusted(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[ok(amount=str(int(UPTO_CEILING) + 1))])
        response = sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert response.cost_usd == pytest.approx(0.05)
        assert response.cost_is_ceiling is True

    def test_exact_rows_unchanged(self, monkeypatch):
        Chain(allowance=0).install(monkeypatch)
        sync_client(Gateway(payment_required())).chat_completion("deepseek/deepseek-chat", MESSAGES)
        row = json.loads(cache.COST_LOG_PATH.read_text().splitlines()[-1])
        assert "cost_basis" not in row

    def test_session_limit_counts_the_ceiling(self, monkeypatch):
        """Unconfirmed ceilings count against max_session_cost: the cap errs safe."""
        Chain().install(monkeypatch)
        gw = Gateway(payment_required())
        client = sync_client(gw, max_session_cost=0.06)
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # upto, books 0.05
        client.chat_completion("deepseek/deepseek-chat", MESSAGES)  # ceiling would breach
        assert gw.schemes == ["upto", "exact"]

    def test_tx_log_marks_ceiling(self):
        row = format_row(
            endpoint="/v1/chat/completions",
            model="deepseek/deepseek-chat",
            in_tokens=1,
            out_tokens=1,
            cost_usd=0.05,
            tx_hash=None,
            cost_basis="upto_ceiling",
        )
        assert row.endswith("(upto ceiling)")
        plain = format_row(
            endpoint="/v1/chat/completions",
            model="m",
            in_tokens=1,
            out_tokens=1,
            cost_usd=0.05,
            tx_hash=None,
        )
        assert "ceiling" not in plain


# ---------------------------------------------------------------------------
# Streaming
# ---------------------------------------------------------------------------


def _sse() -> bytes:
    chunk = {
        "id": "c",
        "object": "chat.completion.chunk",
        "created": 1,
        "model": "deepseek/deepseek-chat",
        "choices": [{"index": 0, "delta": {"content": "hi"}, "finish_reason": "stop"}],
    }
    return f"data: {json.dumps(chunk)}\n\ndata: [DONE]\n\n".encode()


def sse_ok() -> httpx.Response:
    return httpx.Response(
        200,
        content=_sse(),
        headers={"content-type": "text/event-stream", "PAYMENT-RESPONSE": settlement_header()},
    )


class TestStreaming:
    def test_upto_stream_chunks_are_labeled(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[sse_ok()])
        client = sync_client(gw)
        chunks = list(client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        assert gw.schemes == ["upto"]
        assert chunks and all(c.payment_scheme == "upto" for c in chunks)
        assert all(c.cost_is_ceiling is True for c in chunks)
        assert client.get_spending()["ceiling_usd"] == pytest.approx(0.05)

    def test_stream_upto_rejected_retries_exact_before_any_chunk(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), sse_ok()])
        client = sync_client(gw)
        chunks = list(client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        assert gw.schemes == ["upto", "exact"]
        assert chunks[0].payment_scheme == "exact"
        assert chunks[0].cost_usd == pytest.approx(0.001)

    def test_stream_exact_retry_rejected_raises_once(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), verify_failed(), sse_ok()])
        with pytest.raises(PaymentError):
            list(sync_client(gw).chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        assert gw.schemes == ["upto", "exact"]

    def test_stream_rejection_after_a_5xx_replay_never_pays_exact(self, monkeypatch):
        monkeypatch.setattr("time.sleep", lambda _s: None)
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[httpx.Response(502), verify_failed(), sse_ok()])
        with pytest.raises(PaymentError):
            list(sync_client(gw).chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        assert gw.schemes == ["upto", "upto"]

    def test_stream_books_the_ceiling_even_when_the_header_names_an_amount(self, monkeypatch):
        # A stream's PAYMENT-RESPONSE is sent before the upto settle, so an
        # amount on it is not the settled one.
        Chain().install(monkeypatch)
        early = httpx.Response(
            200,
            content=_sse(),
            headers={
                "content-type": "text/event-stream",
                "PAYMENT-RESPONSE": settlement_header("700"),
            },
        )
        gw = Gateway(payment_required(), paid=[early])
        client = sync_client(gw)
        chunks = list(client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        assert chunks[0].cost_is_ceiling is True
        assert chunks[0].cost_usd == pytest.approx(0.05)
        assert client.get_spending()["ceiling_usd"] == pytest.approx(0.05)

    def test_async_stream_upto_rejected_then_exact(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[verify_failed(), sse_ok()])

        async def run():
            client = async_client(gw)
            return [
                c async for c in client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES)
            ]

        chunks = asyncio.run(run())
        assert gw.schemes == ["upto", "exact"]
        assert chunks[0].payment_scheme == "exact"

    def test_async_stream_upto(self, monkeypatch):
        Chain(allowance=0).install(monkeypatch)
        gw = Gateway(payment_required(sponsoring=True), paid=[sse_ok()])

        async def run():
            client = async_client(gw)
            return [
                c async for c in client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES)
            ]

        chunks = asyncio.run(run())
        assert gw.schemes == ["upto"]
        assert "eip2612GasSponsoring" in gw.signed[0]["extensions"]
        assert chunks[0].cost_is_ceiling is True


# ---------------------------------------------------------------------------
# Chain reads (eth_call over a mocked RPC)
# ---------------------------------------------------------------------------


def _word(n: int) -> str:
    return "0x" + format(n, "064x")


class TestChainReads:
    option = find_upto_option(payment_required())
    sponsored = find_upto_option(payment_required(sponsoring=True))

    def _rpc(self, answers: dict[str, Any], calls: list[str]):
        def handler(request: httpx.Request) -> httpx.Response:
            body = json.loads(request.content)
            data = body["params"][0]["data"]
            calls.append(data[:10])
            answer = answers[data[:10]]
            return httpx.Response(200, json=answer)

        return handler

    def test_reads_balance_and_allowance_with_correct_calldata(self):
        seen: list[str] = []

        def handler(request: httpx.Request) -> httpx.Response:
            body = json.loads(request.content)
            assert body["params"][0]["to"] == USDC_BASE
            seen.append(body["params"][0]["data"])
            return httpx.Response(200, json={"jsonrpc": "2.0", "id": 1, "result": _word(5)})

        with httpx.Client(transport=httpx.MockTransport(handler)) as http:
            state = upto._read_state_sync(http, "https://rpc", self.option, TEST_ACCOUNT.address)
        owner = TEST_ACCOUNT.address[2:].lower().rjust(64, "0")
        permit2 = PERMIT2_ADDRESS[2:].lower().rjust(64, "0")
        assert seen == ["0x70a08231" + owner, "0xdd62ed3e" + owner + permit2]
        assert state == UptoChainState(5, 5, None)  # no nonce read without sponsoring

    def test_nonce_read_only_when_permit_needed(self):
        calls: list[str] = []
        answers = {
            "0x70a08231": {"result": _word(10**9)},
            "0xdd62ed3e": {"result": _word(0)},
            "0x7ecebe00": {"result": _word(42)},
        }
        with httpx.Client(transport=httpx.MockTransport(self._rpc(answers, calls))) as http:
            state = upto._read_state_sync(http, "https://rpc", self.sponsored, TEST_ACCOUNT.address)
        assert calls == ["0x70a08231", "0xdd62ed3e", "0x7ecebe00"]
        assert state.permit_nonce == 42

    @pytest.mark.parametrize(
        "answer",
        [{"error": {"code": -32000, "message": "boom"}}, {"result": "0x"}, {"result": None}],
    )
    def test_bad_rpc_answers_raise(self, answer):
        with (
            httpx.Client(
                transport=httpx.MockTransport(lambda r: httpx.Response(200, json=answer))
            ) as http,
            pytest.raises(upto.UptoUnavailable),
        ):
            upto._read_state_sync(http, "https://rpc", self.option, TEST_ACCOUNT.address)

    def test_falls_through_rpcs(self, monkeypatch):
        tried: list[str] = []

        def handler(request: httpx.Request) -> httpx.Response:
            tried.append(str(request.url))
            if "publicnode" in str(request.url):
                return httpx.Response(503)
            return httpx.Response(200, json={"result": _word(9)})

        real_client = httpx.Client
        monkeypatch.setattr(
            upto.httpx,
            "Client",
            lambda **kw: real_client(transport=httpx.MockTransport(handler), **kw),
        )
        state = REAL_READ(self.option, TEST_ACCOUNT.address)
        assert state.balance == 9
        assert tried[0].startswith("https://base.publicnode.com")
        assert tried[-1].startswith("https://mainnet.base.org")

    def test_async_reads(self, monkeypatch):
        answers = {"0x70a08231": _word(10**9), "0xdd62ed3e": _word(0), "0x7ecebe00": _word(3)}

        def handler(request: httpx.Request) -> httpx.Response:
            data = json.loads(request.content)["params"][0]["data"]
            return httpx.Response(200, json={"result": answers[data[:10]]})

        real_async = httpx.AsyncClient
        monkeypatch.setattr(
            upto.httpx,
            "AsyncClient",
            lambda **kw: real_async(transport=httpx.MockTransport(handler), **kw),
        )
        state = asyncio.run(REAL_AREAD(self.sponsored, TEST_ACCOUNT.address))
        assert state == UptoChainState(10**9, 0, 3)

    def test_network_without_rpcs_is_unavailable(self):
        """Arc has no pinned public RPC, so it stays exact."""
        arc = find_upto_option(
            payment_required(
                upto=upto_entry(
                    network="eip155:5042", asset="0x3600000000000000000000000000000000000000"
                )
            )
        )
        assert arc is not None and arc.rpcs == ()
        with pytest.raises(upto.UptoUnavailable):
            REAL_READ(arc, TEST_ACCOUNT.address)


# ---------------------------------------------------------------------------
# An upto-only 402 that upto cannot serve is refused, never signed as EIP-3009
# ---------------------------------------------------------------------------


class TestUptoOnly402:
    def _upto_only(self) -> dict[str, Any]:
        pr = payment_required()
        pr["accepts"] = [upto_entry()]
        return pr

    def test_exact_preference_refuses_instead_of_signing_the_ceiling(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(self._upto_only())
        with pytest.raises(PaymentError, match="only the x402 'upto' scheme"):
            sync_client(gw, payment_scheme="exact").chat_completion(
                "deepseek/deepseek-chat", MESSAGES
            )
        assert gw.signed == []

    def test_unusable_upto_refuses_instead_of_signing_the_ceiling(self, monkeypatch):
        Chain(allowance=0).install(monkeypatch)  # no allowance, no sponsoring
        gw = Gateway(self._upto_only())
        with pytest.raises(PaymentError, match="Nothing was signed"):
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.signed == []

    def test_usable_upto_only_402_still_pays_upto(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(self._upto_only())
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]


class TestExactSpendCapOnSignedAmount:
    def test_cap_uses_the_signed_amount_not_the_lower_body_price(self, monkeypatch):
        # Body price is the base price ($0.0009); the header amount signed is
        # $0.001 (base + tx fee). A $0.00095 cap must refuse.
        from blockrun_llm.types import SpendLimitError

        Chain().install(monkeypatch)
        gw = Gateway(payment_required(with_upto=False), header=False, price_usd="0.0009")
        with pytest.raises(SpendLimitError):
            sync_client(gw, max_cost_per_call=0.00095).chat_completion(
                "deepseek/deepseek-chat", MESSAGES
            )
        assert gw.signed == []


# ---------------------------------------------------------------------------
# PAYMENT_REPLAY on the first send is never answered with an exact payment
# ---------------------------------------------------------------------------


def replay(**extra: Any) -> httpx.Response:
    """The chat route's nonce-claim refusal (blockrun src/lib/payment-nonce.ts)."""
    return httpx.Response(
        402,
        json={
            "error": "Payment authorization already used",
            "message": "Sign a fresh payment authorization for each request.",
            "code": "PAYMENT_REPLAY",
            "payer": TEST_ACCOUNT.address,
            **extra,
        },
    )


def _assert_replay_error(exc: PaymentError) -> None:
    assert "PAYMENT_REPLAY" in str(exc)
    assert "Check your wallet balance" not in str(exc)
    assert exc.status_code == 402
    assert exc.response is not None and exc.response["code"] == "PAYMENT_REPLAY"


class TestReplayNeverPaysExact:
    """A first-send ``PAYMENT_REPLAY`` means the authorization was already used
    by an earlier request that was served and paid (e.g. a proxy duplicated
    the send). Paying exact on top would charge twice."""

    def test_sync(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[replay(), ok()])
        client = sync_client(gw)
        with pytest.raises(PaymentError) as exc:
            client.chat_completion("deepseek/deepseek-chat", MESSAGES)
        _assert_replay_error(exc.value)
        assert gw.schemes == ["upto"]  # exactly one paid POST
        assert client._upto_rejected == {}

    def test_async(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[replay(), ok()])

        async def run():
            await async_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)

        with pytest.raises(PaymentError) as exc:
            asyncio.run(run())
        _assert_replay_error(exc.value)
        assert gw.schemes == ["upto"]

    def test_sync_stream(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[replay(), sse_ok()])
        with pytest.raises(PaymentError) as exc:
            list(sync_client(gw).chat_completion_stream("deepseek/deepseek-chat", MESSAGES))
        _assert_replay_error(exc.value)
        assert gw.schemes == ["upto"]

    def test_async_stream(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[replay(), sse_ok()])

        async def run():
            client = async_client(gw)
            return [
                c async for c in client.chat_completion_stream("deepseek/deepseek-chat", MESSAGES)
            ]

        with pytest.raises(PaymentError) as exc:
            asyncio.run(run())
        _assert_replay_error(exc.value)
        assert gw.schemes == ["upto"]

    def test_recoverable_prior_use_keeps_the_poll_url(self, monkeypatch):
        Chain().install(monkeypatch)
        prior = replay(
            message="This authorization was already used by an earlier request.",
            job_id="job_1",
            poll_url="/api/v1/jobs/job_1",
            recoverable=True,
        )
        gw = Gateway(payment_required(), paid=[prior, ok()])
        with pytest.raises(PaymentError) as exc:
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]
        assert "/api/v1/jobs/job_1" in str(exc.value)
        assert "already used by an earlier request" in str(exc.value)
        assert exc.value.response["poll_url"] == "/api/v1/jobs/job_1"
        assert exc.value.response["recoverable"] is True

    def test_prior_use_markers_without_the_code_still_block_exact(self, monkeypatch):
        Chain().install(monkeypatch)
        body = {"error": "Payment verification failed", "poll_url": "/api/v1/jobs/j"}
        gw = Gateway(payment_required(), paid=[httpx.Response(402, json=body), ok()])
        with pytest.raises(PaymentError):
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]

    def test_unclassified_402_is_not_a_verify_failure(self, monkeypatch):
        Chain().install(monkeypatch)
        gw = Gateway(payment_required(), paid=[httpx.Response(402, json={"error": "?"}), ok()])
        with pytest.raises(PaymentError):
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto"]

    def test_verify_failure_codes_still_fall_back(self, monkeypatch):
        Chain().install(monkeypatch)
        unfunded = httpx.Response(
            402, json={"error": "Payment verification failed", "code": "PAYMENT_UNFUNDED"}
        )
        gw = Gateway(payment_required(), paid=[unfunded, ok()])
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact"]

    def test_fresh_challenge_402_still_falls_back(self, monkeypatch):
        # The gateway answered the upto payment with a new challenge: it was
        # not accepted at all, so nothing was used.
        Chain().install(monkeypatch)
        challenge = httpx.Response(
            402,
            json={"error": "Payment Required"},
            headers={"payment-required": b64(payment_required())},
        )
        gw = Gateway(payment_required(), paid=[challenge, ok()])
        sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert gw.schemes == ["upto", "exact"]

    def test_upto_only_402_refused_by_the_gateway_says_so(self, monkeypatch):
        Chain().install(monkeypatch)
        pr = payment_required()
        pr["accepts"] = [upto_entry()]
        gw = Gateway(pr, paid=[verify_failed(), ok()])
        with pytest.raises(PaymentError, match="the gateway refused it") as exc:
            sync_client(gw).chat_completion("deepseek/deepseek-chat", MESSAGES)
        assert "Nothing was signed" not in str(exc.value)
        assert gw.schemes == ["upto"]


# ---------------------------------------------------------------------------
# The shared EIP-3009 signer never signs an upto requirement
# ---------------------------------------------------------------------------


class TestSharedSignerRefusesUpto:
    def _upto_only(self) -> dict[str, Any]:
        pr = payment_required()
        pr["accepts"] = [upto_entry()]
        return pr

    def test_extract_payment_details_refuses_upto_only(self):
        from blockrun_llm.x402 import extract_payment_details

        with pytest.raises(ValueError, match="only the x402 'upto' scheme"):
            extract_payment_details(self._upto_only())

    def test_extract_payment_details_allow_upto_returns_it(self):
        from blockrun_llm.x402 import extract_payment_details

        details = extract_payment_details(self._upto_only(), allow_upto=True)
        assert details["scheme"] == "upto"
        assert details["amount"] == UPTO_CEILING

    def test_extract_payment_details_prefers_exact_over_a_leading_upto(self):
        from blockrun_llm.x402 import extract_payment_details

        pr = payment_required()
        pr["accepts"] = [upto_entry(), exact_entry()]
        assert extract_payment_details(pr)["scheme"] == "exact"

    def test_create_payment_payload_refuses_a_non_exact_scheme(self):
        from blockrun_llm.x402 import create_payment_payload

        with pytest.raises(ValueError, match="cannot be signed as an EIP-3009"):
            create_payment_payload(
                TEST_ACCOUNT, TEST_RECIPIENT, UPTO_CEILING, asset=USDC_BASE, scheme="upto"
            )

    def test_create_payment_payload_default_and_v1_none_are_exact(self):
        from blockrun_llm.x402 import create_payment_payload

        for kwargs in ({}, {"scheme": None}, {"scheme": "exact"}):
            payload = decode(create_payment_payload(TEST_ACCOUNT, TEST_RECIPIENT, "1000", **kwargs))
            assert payload["accepted"]["scheme"] == "exact"

    def test_image_client_signs_nothing_for_an_upto_only_402(self):
        from blockrun_llm.image import ImageClient

        gw = Gateway(self._upto_only())
        client = ImageClient(private_key=TEST_PRIVATE_KEY)
        client._client = httpx.Client(transport=httpx.MockTransport(gw))
        with pytest.raises(ValueError, match="only the x402 'upto' scheme"):
            client.generate("a cat")
        assert gw.signed == []
